export enum GetProductsOrderByOptionsEnum {
  PRODUCT_CODE = 'PRODUCT_CODE',
  PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION',
  MASTER_LINE_CODE = 'MASTER_LINE_CODE',
  MASTER_LINE_DESCRIPTION = 'MASTER_LINE_DESCRIPTION',
  LINE_CODE = 'LINE_CODE',
  LINE_DESCRIPTION = 'LINE_DESCRIPTION',
  MATERIAL_FAMILY_CODE = 'MATERIAL_FAMILY_CODE',
  MATERIAL_FAMILY_DESCRIPTION = 'MATERIAL_FAMILY_DESCRIPTION',
  COMMERCIAL_PRODUCT_CODE = 'COMMERCIAL_PRODUCT_CODE',
  COMMERCIAL_PRODUCT_DESCRIPTION = 'COMMERCIAL_PRODUCT_DESCRIPTION',
  STOCK_GROUP_CODE = 'STOCK_GROUP_CODE',
  STOCK_GROUP_DESCRIPTION = 'STOCK_GROUP_DESCRIPTION',
  OUT_LINE = 'OUT_LINE',
  OUT_LINE_IMPORT = 'OUT_LINE_IMPORT',
  CRITICAL_ITEM = 'CRITICAL_ITEM'
}

export enum GetProductsOrderByOptionsValuesEnum {
  PRODUCT_CODE = 'codigoproduto',
  PRODUCT_DESCRIPTION = 'descricaoproduto',
  MASTER_LINE_CODE = 'codigolinhapai',
  MASTER_LINE_DESCRIPTION = 'descricaolinhapai',
  LINE_CODE = 'codigolinha',
  LINE_DESCRIPTION = 'descricaolinha',
  MATERIAL_FAMILY_CODE = 'codigofamiliamaterial',
  MATERIAL_FAMILY_DESCRIPTION = 'descricaofamiliamaterial',
  COMMERCIAL_PRODUCT_CODE = 'codigoprodutocomercial',
  COMMERCIAL_PRODUCT_DESCRIPTION = 'descricaoprodutocomercial',
  STOCK_GROUP_CODE = 'codigogrupoestoque',
  STOCK_GROUP_DESCRIPTION = 'descricaogrupoestoque',
  OUT_LINE = 'foralinha',
  OUT_LINE_IMPORT = 'foralinhaimportacao',
  CRITICAL_ITEM = 'itemcritico'
}
