/* eslint-disable camelcase */
/* eslint-disable no-shadow */
export enum CompanyEnum {
  BRITANIA_ELETRODOMESTICOS = 'BRITÂNIA ELETRODOMÉSTICOS S/A',
  BRITANIA_ELETRONICOS = 'BRITÂNIA ELETRÔNICOS S/A',
  PHILCO_ELETRONICOS = 'PHILCO ELETRÔNICOS S/A',
  TODAS_EMPRESAS = 'TODAS AS EMPRESAS DO GRUPO'
}
