// eslint-disable-next-line no-shadow
export enum PermissionsEnum {
  APROVAR = 'APROVAR',
  REPROVAR = 'REPROVAR',
  INCLUIR = 'INCLUIR',
  EDITAR = 'EDITAR',
  EXCLUIR = 'EXCLUIR',
  INATIVAR = 'INATIVAR',
  IMPORTACAO_EM_MASSA = 'IMPORTACAO_EM_MASSA',
  ACESSO_A_INFORMACAO_CONFIDENCIAL = 'ACESSO_A_INFORMACAO_CONFIDENCIAL',
  EDITAR_RANKING_DE_CLIENTE = 'EDITAR_RANKING_DE_CLIENTE'
}
